import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

f = r'F:\EasyTimer\AGENTS.md'

content = []
content.append('# AGENTS.md')
content.append('')
content.append('> EasyTimer — 一个极简的 Android 定时关闭应用工具。本文档为 Agent 提供项目概览和开发指引。')
content.append('')
content.append('## 项目概述')
content.append('')
content.append('- **包名**: com.jussicodes.easytimer')
content.append('- **语言**: Kotlin')
content.append('- **架构**: MVVM + Repository Pattern')
content.append('- **UI 技术栈**: Jetpack Compose（单 Activity 架构）')
content.append('- **最低 SDK**: 26 (Android 8.0)')
content.append('- **目标 SDK**: 34 (Android 14)')
content.append('- **构建系统**: Gradle Kotlin DSL（AGP 8.5.0，Kotlin 1.9.0）')
content.append('')
content.append('## 核心功能')
content.append('')
content.append('1. **选择应用** - 浏览已安装应用列表（显示图标、名称、包名），支持搜索、收藏、最近使用排序')
content.append('2. **设置定时关闭** - 选择 5/10/30/60 分钟或自定义分钟数；默认使用上次设置的时长')
content.append('3. **前台倒计时服务** - 前台服务 + 通知栏倒计时，支持暂停/继续/取消/立即关闭/增加5分钟')
content.append('4. **Root 强制关闭** - 到点或用户点击时通过 su -c am force-stop 包名 真正杀死目标应用')
content.append('5. **快捷通知** - 通知栏直接操作（暂停/继续/增加5分钟/取消/立即关闭）')
content.append('6. **快捷设置磁贴** - 系统 QS 磁贴支持（显示定时状态 / 取消任务 / 打开 App）')
content.append('7. **完成后自毁** - 定时关闭目标应用后，自动关闭 EasyTimer 自身（需 Root），开关状态持久化')
content.append('')
content.append('## 目录结构')
content.append('')
content.append('`')
content.append('app/src/main/java/com/jussicodes/easytimer/')
content.append('+-- data/')
content.append('|   +-- PreferencesRepository.kt       # DataStore 持久化（收藏、最近使用、上次时长、自毁开关）')
content.append('+-- model/')
content.append('|   +-- Models.kt                       # AppInfo, Screen 枚举, TimerState 密封类')
content.append('+-- root/')
content.append('|   +-- RootShellManager.kt             # Root 权限检测 + 执行 shell 命令（su）')
content.append('+-- service/')
content.append('|   +-- TimerForegroundService.kt       # 前台服务：倒计时、通知管理、Root 关闭执行、加5分钟')
content.append('|   +-- QuickTimerTileService.kt        # QS 磁贴：快速操作')
content.append('+-- ui/')
content.append('|   +-- screens/')
content.append('|   |   +-- HomeScreen.kt               # 首页：应用列表 + 搜索 + 收藏 + 最近使用')
content.append('|   |   +-- TimerSetupScreen.kt          # 定时设置页：预设时间 + 自定义输入')
content.append('|   |   +-- ActiveTimerScreen.kt         # 倒计时中页：进度环 + 控制按钮')
content.append('|   |   +-- SettingsScreen.kt            # 设置页：自毁开关 + Root 状态')
content.append('|   +-- theme/')
content.append('|       +-- Color.kt                     # Material 3 颜色')
content.append('|       +-- Theme.kt                     # EasyTimerTheme + 深色/浅色/DynamicMaterial')
content.append('|       +-- Type.kt                      # 默认排版')
content.append('+-- viewmodel/')
content.append('|   +-- MainViewModel.kt                # 主 ViewModel：状态管理 + 业务逻辑')
content.append('+-- MainActivity.kt                     # 入口 Activity（4 个 Screen 路由）')
content.append('`')
content.append('')
content.append('## 关键文件速查')
content.append('')
content.append('| 文件 | 职责 |')
content.append('|---|---|')
content.append('| pp/build.gradle.kts | Compose BOM, DataStore, Material 3 |')
content.append('| pp/src/main/AndroidManifest.xml | 权限：FOREGROUND_SERVICE, POST_NOTIFICATIONS, RECEIVE_BOOT_COMPLETED, QUERY_ALL_PACKAGES |')
content.append('| MainViewModel.kt | 应用列表加载、搜索过滤、收藏/最近排序、定时启动/暂停/取消/立即关闭、自毁持久化 |')
content.append('| TimerForegroundService.kt | CountDownTimer、前台通知、Root shell 执行、多 Action 分发、加5分钟 |')
content.append('| RootShellManager.kt | 单例，isRootAvailable() + forceStopApp() |')
content.append('| PreferencesRepository.kt | DataStore：收藏集、最近集（最多10）、上次持续时长、自毁开关 |')
content.append('')
content.append('## 数据流')
content.append('')
content.append('`')
content.append('MainActivity')
content.append('  +-- AppContent() --> MainViewModel')
content.append('          +-- HomeScreen        搜索/收藏/选择应用')
content.append('          +-- TimerSetupScreen  选择时长（默认恢复上次设置）')
content.append('          +-- ActiveTimerScreen 控制倒计时')
content.append('          +-- SettingsScreen    自毁开关')
content.append('')
content.append('MainViewModel')
content.append('  +-- filteredApps (StateFlow) <-- combine(全部应用, 搜索词, 收藏, 最近)')
content.append('  +-- timerState (StateFlow)   <-- TimerForegroundService._timerState')
content.append('  +-- selectedPreset (StateFlow) <-- 初始为0，从 lastDuration 恢复')
content.append('  +-- selfDestruct (StateFlow) <-- 从 DataStore 恢复/设置')
content.append('      +-- startTimer() --> 启动 TimerForegroundService.ACTION_START')
content.append('')
content.append('TimerForegroundService')
content.append('  +-- ACTION_START         --> 启动倒计时')
content.append('  +-- ACTION_PAUSE         --> 暂停')
content.append('  +-- ACTION_RESUME        --> 继续')
content.append('  +-- ACTION_CANCEL        --> 取消')
content.append('  +-- ACTION_FORCE_STOP_NOW --> 执行 Root shell 关闭 + 通知')
content.append('  +-- ACTION_ADD_5_MIN     --> 倒计时延长5分钟（totalSeconds + 300）')
content.append('`')
content.append('')
content.append('## 数据持久化')
content.append('')
content.append('| DataStore Key | 类型 | 说明 |')
content.append('|---|---|---|')
content.append('| avorite_packages | Set<String> | 收藏的应用包名列表 |')
content.append('| ecent_packages | Set<String> | 最近使用的应用包名（最多10个） |')
content.append('| last_duration_minutes | Int | 上次设置的倒计时时长（分钟） |')
content.append('| selfdestruct_enabled | Boolean | 完成后自毁开关状态 |')
content.append('')
content.append('## 数据流（持久化）')
content.append('')
content.append('`')
content.append('PreferencesRepository')
content.append('  +-- DataStore (easytimer_prefs)')
content.append('      +-- favoritePackages  Flow<Set<String>>')
content.append('      +-- recentPackages    Flow<Set<String>>')
content.append('      +-- lastDuration      Flow<Int>       --> 初始15，启动时同步到 _selectedPreset')
content.append('      +-- selfDestructEnabled Flow<Boolean>')
content.append('')
content.append('MainViewModel')
content.append('  +-- observePreferences() 监听 DataStore 更新所有 StateFlow')
content.append('  +-- toggleSelfDestruct() 写入 DataStore + 更新 StateFlow')
content.append('  +-- startTimer()/launchAndStartTimer() 不重置 selfDestruct（持久化开关）')
content.append('`')
content.append('')
content.append('## 权限清单')
content.append('')
content.append('| 权限 | 用途 |')
content.append('|---|---|')
content.append('| FOREGROUND_SERVICE | 前台倒计时服务 |')
content.append('| FOREGROUND_SERVICE_SPECIAL_USE | Android 14+ 前台类型声明 |')
content.append('| POST_NOTIFICATIONS | Android 13+ 通知权限（运行时申请） |')
content.append('| RECEIVE_BOOT_COMPLETED | 开机恢复（预留） |')
content.append('| QUERY_ALL_PACKAGES | 列出所有已安装应用 |')
content.append('| PACKAGE_USAGE_STATS | 预留 |')
content.append('')
content.append('## 开发注意事项')
content.append('')
content.append('- **单 Activity 路由**：通过 Screen 枚举切换 4 个 Composable（HOME / TIMER_SETUP / ACTIVE_TIMER / SETTINGS），无 Navigation 依赖')
content.append('- **应用列表缓存**：MainViewModel 在 init 中异步加载（IO 线程），按包名缓存为 AppInfo 列表')
content.append('- **Root 检测**：执行 su -c echo root_ok 判断，不阻塞主线程')
content.append('- **前台服务启动限制**：Android 14 对非 UI 线程启动前台服务有约束，ViewModel 已用 try-catch 处理 ForegroundServiceStartNotAllowedException')
content.append('- **通知图标**：使用 ndroid.R.drawable.ic_dialog_info 作为通知小图标')
content.append('- **颜色主题**：默认使用 Material You 动态取色（Android 12+），否则回退到预设紫色/粉色色系')
content.append('- **UI 设计原则**：极简、深色模式友好、最多 3 次点击完成操作')
content.append('- **文件编码**：所有 *.kt 文件必须使用 **UTF-8** 编码（无 BOM），否则中文会出现乱码')
content.append('- **默认倒计时**：_selectedPreset 初始值为 0，启动时从 lastDuration 同步恢复为上次使用的时长')
content.append('- **自毁开关**：	oggleSelfDestruct() 写入 DataStore，observePreferences() 恢复状态，启动定时后不自动重置')
content.append('')
content.append('## 构建命令')
content.append('')
content.append('`powershell')
content.append('.\\gradlew assembleDebug          # Debug APK')
content.append('.\\gradlew assembleRelease        # Release APK')
content.append('.\\gradlew :app:connectedAndroidTest  # 仪器测试')
content.append('`')
content.append('')
content.append('## 代码风格约定')
content.append('')
content.append('- 使用 kotlin.code.style=official（Kotlin 官方编码约定）')
content.append('- 命名空间为 com.jussicodes.easytimer')
content.append('- 不使用第三方导航库，手动 Composable 路由')
content.append('- 不引入 Flutter / React Native')
content.append('- 不添加社交、账号、云同步、统计、广告')

with open(f, 'w', encoding='utf-8') as fh:
    fh.write(chr(10).join(content) + chr(10))

print('Done. Lines:', len(content))

